{% set name = "optuna" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03355542f297c67093d361221e8b3bd9bebb19e5476800ecc2fb95a346278e89

build:
  number: 0
  entry_points:
    - optuna = optuna.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - alembic
    - cliff
    - colorlog
    - joblib
    - numpy
    - python >=3.5
    - scipy
    - six
    - sqlalchemy >=1.1.0
    - tqdm

test:
  imports:
    - optuna
    - optuna.integration
    - optuna.pruners
    - optuna.samplers
    - optuna.samplers.tpe
    - optuna.storages
    - optuna.storages.rdb
    - optuna.testing
    - tests
    - tests.integration_tests
    - tests.pruners_tests
    - tests.samplers_tests
    - tests.storages_tests
    - tests.storages_tests.rdb_tests
  commands:
    - optuna --help
  source_files:
    - tests

about:
  home: https://optuna.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A hyperparameter optimization framework
  doc_url: https://optuna.readthedocs.io/
  dev_url: https://github.com/optuna/optuna

extra:
  recipe-maintainers:
    - g-votte
    - hvy
    - iwiwi
    - sile
    - smly
    - toshihikoyanase
