{% set name = "optuna" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "322df88051b60f3f42c89285a9434f01b650a4b0b3bcd7b46fbc328424df4eda"

build:
  number: 0
  entry_points:
    - optuna = optuna.cli:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - alembic
    - cliff
    - colorlog
    - joblib
    - numpy
    - python >=3.5
    - scipy
    - six
    - sqlalchemy >=1.1.0
    - tqdm

test:
  imports:
    - optuna
    - optuna.integration
    - optuna.pruners
    - optuna.samplers
    - optuna.samplers.tpe
    - optuna.storages
    - optuna.storages.rdb
    - optuna.testing
    - tests
    - tests.integration_tests
    - tests.pruners_tests
    - tests.samplers_tests
    - tests.storages_tests
    - tests.storages_tests.rdb_tests
  commands:
    - optuna --help
  source_files:
    - tests

about:
  home: https://optuna.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A hyperparameter optimization framework
  doc_url: https://optuna.readthedocs.io/
  dev_url: https://github.com/optuna/optuna

extra:
  recipe-maintainers:
    - g-votte
    - hvy
    - iwiwi
    - sile
    - smly
    - toshihikoyanase
