{% set name = "optuna" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 683d8693643a761a41d251a6b8e13263b24acacf9fc46a9233d5f6aa3ce5c683

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - optuna = optuna.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - alembic >=1.5.0
    - cmaes >=0.9.1
    - colorlog
    - numpy
    - packaging >=20.0
    - python
    - pyyaml
    - sqlalchemy >=1.3.0
    - tqdm

test:
  imports:
    - optuna
  requires: 
    - pip
  commands:
    - pip check
    - optuna --help

about:
  home: https://optuna.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A hyperparameter optimization framework
  description: |
    Optuna is an automatic hyperparameter optimization software framework, 
    particularly designed for machine learning. 
    It features an imperative, define-by-run style user API. 
  doc_url: https://optuna.readthedocs.io/
  dev_url: https://github.com/optuna/optuna

extra:
  recipe-maintainers:
    - c-bata
    - contramundum53
    - g-votte
    - himkt
    - HideakiImamura
    - hvy
    - iwiwi
    - knshnb
    - not522
    - sile
    - smly
    - toshihikoyanase
    - ytsmiling
